<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rpa</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>RPA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rules</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#emissions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#default</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.rpa</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^|[^\[\-])((#).*)$</string>
			<key>repository</key>
			<dict>
				<key>default</key>
				<dict>
					<key>match</key>
					<string>.*</string>
					<key>name</key>
					<string>comment.line.number-sign.rpa</string>
				</dict>
				<key>emissions</key>
				<dict>
					<key>match</key>
					<string>#!(?:noemit|emit(?:id|none|all)?)</string>
					<key>name</key>
					<string>keyword.control.directive.rpa</string>
				</dict>
			</dict>
		</dict>
		<key>rules</key>
		<dict>
			<key>begin</key>
			<string>(\w+)\s*::=</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.rule.$1.rpa</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=\s*\w+\s*::=)</string>
			<key>name</key>
			<string>meta.function.rule.$1.rpa</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escapes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule-refs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dots</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>dots</key>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.entity.dot.rpa</string>
				</dict>
				<key>escapes</key>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.rpa</string>
				</dict>
				<key>operators</key>
				<dict>
					<key>match</key>
					<string>\?|\+|\*|\-|\^|\|</string>
					<key>name</key>
					<string>keyword.operator.quantifier.rpa</string>
				</dict>
				<key>rule-refs</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.rule-name.begin.rpa</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.rule-name.end.rpa</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;)\w+(&gt;)</string>
					<key>name</key>
					<string>variable.other.rpa</string>
				</dict>
				<key>strings</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#double</string>
						</dict>
					</array>
					<key>repository</key>
					<dict>
						<key>double</key>
						<dict>
							<key>begin</key>
							<string>"</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.rpa</string>
								</dict>
							</dict>
							<key>end</key>
							<string>"</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.rpa</string>
								</dict>
							</dict>
							<key>name</key>
							<string>string.quoted.double.rpa</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\\.</string>
									<key>name</key>
									<string>constant.character.escape.rpa</string>
								</dict>
							</array>
						</dict>
						<key>single</key>
						<dict>
							<key>begin</key>
							<string>'</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.rpa</string>
								</dict>
							</dict>
							<key>end</key>
							<string>'</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.rpa</string>
								</dict>
							</dict>
							<key>name</key>
							<string>string.quoted.single.rpa</string>
						</dict>
					</dict>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rpa</string>
	<key>uuid</key>
	<string>B2222D78-E57F-4992-9F20-4082DEE5129A</string>
</dict>
</plist>
